name: Test

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release_test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['lts', '1.11', 'nightly']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x64]
        include:
          - version: 'lts'
            os: 'macOS-latest'
            arch: 'aarch64'
          - version: '1.11'
            os: 'macOS-latest'
            arch: 'aarch64'
          - version: 'nightly'
            os: 'macOS-latest'
            arch: 'aarch64'

    steps:
      - uses: actions/checkout@v4

      # install Julia
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # set-up packages
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
